[protocol]
name = "fluid-aquarium"
scope = "fluidtokens"
version = "0.1.0"
description = "Babel fees and scheduled transactions on Cardano by FluidTokens"
main = "main.tx3"
readme = "README.md"

[ledger]
family = "cardano"

